version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "DB_APP_NAME=lingo"
      - "DB_APP_USER=lingo"
      - "DB_APP_PASS=lingo"
    volumes:
      - "./development/data:/var/data/db"
